name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build --target test --tag test .
    - run: docker run test todo_app/test/unit_tests
    - run: docker run --env-file .env.docker test todo_app/test/integration_tests