name: Continuous Integration
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'C4 Diagrams/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'C4 Diagrams/**'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build --target test --tag test .
    - run: docker run test todo_app/test/unit_tests
    - run: docker run --env-file .env.docker test todo_app/test/integration_tests
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/dev-ops-todo
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          target: production
          tags: dsdanielh/dev-ops-todo:prod2
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
      name: Refresh azure deployment using webhook
      runs-on: ubuntu-latest
      needs: push_to_registry
      if: github.ref == 'refs/heads/main'
      steps:
        - name: Refresh azure deployment using webhook
          run: |
            curl -dH --fail -X POST '${{ secrets.AZURE_WEBHOOK }}'
